version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=Twitter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=131329
      - POSTGRES_HOST=db
      - DJANGO_SECRET_KEY=django-insecure-^t5$ydvyemeq&x-m)yzbgh&^jq2v(bgi6@+dfk8#yc=_15+6_x
      - DJANGO_SECRET_KEY_JWT=hfasoj=rajfnajn+arjsafoj_amfojfaowjx
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: Twitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 131329
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
